import { ContactMail } from './contact-mail';
import './still.css';

const moments = [
  'Știi că timpul este limitat, dar în jurul tău se vorbește doar despre tratamente și mâncare.',
  'Ai ceva important de spus, dar nu vrei să îi protejezi pe ceilalți lăsându-l nespus.',
  'Vrei să poți vorbi sincer despre frică, dorințe sau relațiile importante, fără să fii grăbit(ă) spre optimism.',
  'Te gândești cine ar vrea să fie aproape, ce ai vrea să rămână celor dragi sau cum vor fi îngrijite animalele tale.',
];
const limits = ['nu ofer îngrijire medicală sau recomandări clinice', 'nu înlocuiesc terapia, sprijinul psihiatric sau consilierea juridică', 'nu organizez funeralii și nu ofer servicii religioase', 'nu sunt serviciu de urgență și nu promit disponibilitate 24/7 sau prezență garantată în ultimele ore', 'întâlnirile se stabilesc în funcție de disponibilitatea mea reală, de regulă seara și în weekend'];
const stillMatters = ['O persoană pe care vrei să o vezi', 'Un loc sau un lucru mic care ți-ar face bine', 'Ce ai vrea să spui sau să lași în urmă', 'Ce ai vrea să știe familia despre animalele tale'];

export default function Home() {
  return <main>
    <nav className="topbar"><a className="wordmark" href="#acasa">death<span>doula</span>.ro</a><div className="nav-links"><a href="#insotire">Însoțire</a><a href="#despre">Despre mine</a><a href="#intrebari">Întrebări</a></div><a className="nav-cta" href="#contact">Contact</a></nav>
    <section id="acasa" className="hero">
      <video className="hero-video" autoPlay muted loop playsInline poster="/media/tea-hero-poster.png"><source src="/media/tea-hero.mp4" type="video/mp4" /></video><div className="hero-shade" />
      <div className="hero-content"><p className="eyebrow light">Însoțire conversațională non-medicală · București</p><h1>Nu trebuie să găsești<br />cuvintele perfecte.</h1><div className="hero-bottom"><p>Întâlniri în persoană, în București, pentru conversații despre apropierea morții — fără grabă și fără să fii nevoit(ă) să protejezi pe nimeni.</p><a className="round-link" href="#contact"><span>Începem cu o conversație</span><b>↘</b></a></div></div><p className="hero-caption">Un timp împreună, fără grabă.</p>
    </section>
    <section className="statement section-pad"><p className="eyebrow">O prezență calmă</p><h2>pentru oamenii care se apropie de moarte și nu vor să traverseze această perioadă în tăcere.</h2><p className="statement-note">Nu trebuie să știi ce să spui. Nu trebuie să porți totul singur(ă).</p></section>
    <section id="insotire" className="moments section-pad"><div className="section-intro"><p className="eyebrow">Poate ai ajuns aici pentru că</p><p>Nu există o reacție „corectă” în fața morții. Există doar nevoia de a nu rămâne singur(ă) cu ce e greu de rostit.</p></div><ol>{moments.map((moment,index)=><li key={moment}><span>0{index+1}</span><p>{moment}</p><b>↘</b></li>)}</ol></section>
    <section className="service-grid section-pad"><div><p className="eyebrow">Cum pot fi alături</p><h2>O întâlnire poate fi primul pas. Sau poate continua, atât cât are sens.</h2></div><div className="service-copy"><p>Ne vedem față în față, în București. Într-o întâlnire putem vorbi despre teamă, relațiile importante, dorințele pentru perioada care urmează sau lucrurile rămase nespuse.</p><p>Putem pune în cuvinte dorințe personale: cine ai vrea să fie prezent, ce muzică să se audă, ce fel de rămas-bun ți s-ar potrivi sau ce mesaje ai vrea să ajungă la cei dragi. Dacă îți dorești, putem aduna amintiri, povești, înregistrări sau scrisori într-o formă care să rămână.</p><p>Întâlnirile pot fi unice sau recurente. Nu există o agendă obligatorie și nu trebuie să „rezolvi” nimic. Stabilim ritmul împreună, în funcție de situația ta și de disponibilitatea mea reală.</p><p>Dacă ești aparținător, îmi poți scrie ca să vedem dacă acest tip de însoțire ar fi potrivit pentru persoana dragă. Întâlnirile mele rămân individuale și au în centru persoana care se apropie de finalul vieții.</p><a className="text-link" href="#contact">Spune-mi pe scurt ce se întâmplă</a></div></section>
    <section className="still section-pad"><div className="still-intro"><p className="eyebrow">Încă</p><h2>Lucruri care merită să se întâmple.</h2><p>Nu toate dorințele trebuie să fie mari. Uneori înseamnă o persoană, o plimbare, o melodie, o rețetă sau un plan liniștitor pentru cineva — inclusiv pentru animalele tale.</p></div><ul>{stillMatters.map((item, index) => <li key={item}><span>0{index + 1}</span><p>{item}</p></li>)}</ul><p className="still-note">Putem începe de aici, fără să transformăm dorințele într-o listă de bifat.</p></section>
    <section id="despre" className="about section-pad"><div className="about-copy"><p className="eyebrow">Despre mine</p><h2>Nu am răspunsuri prestabilite. Dar pot să rămân în conversație când e greu.</h2><p className="large-copy">Sunt Nicole. Nu sunt medic, asistentă sau psihoterapeut și nu ofer îngrijire medicală ori intervenție terapeutică.</p><p>După 18 ani de lucru în relații cu oamenii, am învățat să ascult cu atenție, să rămân calmă într-o conversație dificilă și să nu grăbesc pe cineva spre un răspuns.</p><p>Am ajuns spre acest domeniu după pierderi din propria familie. Am văzut cât de des moartea devine un subiect evitat, chiar și atunci când este foarte aproape. Studiez în prezent domeniul însoțirii la finalul vieții.</p><p>Sunt o persoană spirituală, fără apartenență la o religie anume. Respect credința, ritualurile și valorile fiecărui om, precum și alegerea de a nu avea o credință religioasă.</p><a className="text-link" href="#intrebari">Mai multe despre ce este o death doula <span>→</span></a></div><figure className="about-image"><img src="/media/nicole-about.png" alt="Nicole, într-un spațiu calm, luminos" /><figcaption>Nicole · București</figcaption></figure></section>
    <section className="limits section-pad"><div><p className="eyebrow">E important să fie clar</p><h2>Ce nu fac</h2></div><ul>{limits.map(limit=><li key={limit}><span>—</span>{limit}</li>)}</ul></section>
    <section id="intrebari" className="faq section-pad">
      <div><p className="eyebrow">Întrebări frecvente</p><h2>Ce este, de fapt, o death doula?</h2></div>
      <div className="faq-copy">
        <p>O death doula oferă sprijin non-medical în jurul finalului vieții: prezență, conversație și continuitate. Nu ia moartea din drum și nu înlocuiește îngrijirea medicală sau sprijinul psihologic. Poate face loc unei conversații care altfel ar rămâne nespusă.</p>
        <details><summary>Trebuie să știm deja ce ne dorim?</summary><p>Nu. O conversație poate începe exact de acolo: cu neliniștea, confuzia sau cu ce nu reușești încă să spui.</p></details>
        <details><summary>Lucrezi și cu familia?</summary><p>Dacă ești aparținător, îmi poți scrie pentru a vedea dacă acest tip de însoțire ar fi potrivit pentru persoana dragă. Întâlnirile mele sunt individuale și au în centru persoana care se apropie de finalul vieții; nu ofer consiliere individuală pentru aparținători.</p></details>
        <details><summary>Care este pregătirea ta?</summary><p>Nu sunt medic, asistentă sau psihoterapeut. Am 18 ani de experiență în relații cu oamenii și studiez în prezent domeniul însoțirii la finalul vieții. Lucrez exclusiv non-medical, cu limite clare.</p></details>
      </div>
    </section>
    <section id="contact" className="contact section-pad"><div className="contact-head"><p className="eyebrow light">Primul contact</p><h2>Spune-mi puțin<br />despre ce se întâmplă.</h2><p>Putem începe cu o conversație telefonică scurtă, de 10–15 minute, ca să vedem dacă întâlnirea ar fi potrivită. Poți scrie și dacă ești aparținător.</p></div><div className="contact-form"><ContactMail /><p className="form-note">Acest spațiu este dedicat exclusiv conversațiilor legate de finalul vieții. Nu este un serviciu de urgență și nu înlocuiește sprijinul medical sau psihologic.</p></div></section>
    <footer><span>© 2026 deathdoula.ro</span><a href="#acasa">Înapoi sus ↑</a></footer>
  </main>;
}
